# Generated by Django 6.0.1 on 2026-02-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent_team', models.CharField(max_length=50)),
                ('score_goal_real_madrid', models.PositiveIntegerField()),
                ('score_goal_opponent', models.PositiveIntegerField()),
                ('referee', models.CharField(max_length=100, unique=True)),
                ('stadium', models.CharField(max_length=50)),
                ('players', models.ManyToManyField(related_name='matches', to='players.player')),
            ],
        ),
    ]
