# Generated by Django 6.0.1 on 2026-02-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.CharField(max_length=100),
        ),
    ]
