# Generated by Django 6.0.1 on 2026-02-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fans', '0001_initial'),
        ('matches', '0002_alter_match_referee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_comments', to='fans.fan')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_comments', to='matches.match')),
            ],
        ),
    ]
