# Generated by Django 6.0.1 on 2026-02-01 12:20

import players.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'CentralBack'), ('RB', 'RightBack'), ('LB', 'LeftBack'), ('CM', 'CentralMid'), ('CAM', 'CentralAttackMid'), ('DMF', 'DefensiveMid'), ('RW', 'RightWing'), ('LW', 'LeftWing'), ('ST', 'Striker')])),
                ('shirt_number', models.PositiveIntegerField(unique=True, validators=[players.validators.validate_shirt_number])),
                ('age', models.PositiveIntegerField(validators=[players.validators.validate_age])),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
