# Generated by Django 6.0.1 on 2026-02-15 20:36

import players.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='shirt_number',
            field=models.PositiveIntegerField(validators=[players.validators.validate_shirt_number]),
        ),
    ]
